apiVersion: v1
kind: Pod
metadata:
  name: hello-docker-pod
  labels:
    app: hello-docker
spec:
  containers:
  - name: hello-docker
    image: dockerhub-gulcan82/hello-docker-app:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
